project:
  type: book
  output-dir: docs

book:
  title: "Calculus: Formulas and Theorems"
  author: "Daniel Vartanian"
  site-url: https://danielvartan.github.io/calculus/
  repo-url: https://github.com/danielvartan/calculus/
  repo-branch: main
  sharing: [twitter]
  chapters:
    - index.qmd
    - part: qmd/pre-calculus.qmd
      chapters: 
        - qmd/zf-axioms.qmd
        - qmd/numbers.qmd
        - qmd/algebra.qmd
        - qmd/progressions.qmd
        - qmd/logarithms.qmd
        - qmd/geometry.qmd
        - qmd/trigonometry.qmd
        - qmd/functions.qmd
    - part: qmd/univariate-calculus.qmd
      chapters: 
        - qmd/limits.qmd
        - qmd/derivatives.qmd
        - qmd/applications-of-derivatives.qmd
        - qmd/series.qmd
        - qmd/integrals.qmd
        - qmd/table-of-integrals.qmd
    - part: qmd/multivariate-calculus.qmd
      chapters: 
        - qmd/funcion-of-several-variables.qmd
        - qmd/partial-derivatives.qmd
        - qmd/taylor-expansion.qmd
        - qmd/max-min-analysis.qmd
        - qmd/matrices.qmd
        - qmd/systems-of-equations.qmd
    - qmd/useful-resources.qmd
    - qmd/references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
